import { DocumentItem, Profile, OrderItem, Transaction, AdminUser, PayoutRequest } from '@/types/database.types';

export const MOCK_ADMINS: AdminUser[] = [
  {
    id: 'adm_super_01',
    email: 'orukari878@gmail.com',
    full_name: 'Super Admin (Owner)',
    permission: 'SUPER_ADMIN',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=250',
    last_login: 'Active Now',
    is_active: true,
  },
  {
    id: 'adm_02',
    email: 'disputes@studynotehub.com',
    full_name: 'Barrister K. Nnamdi (Dispute Mediator)',
    permission: 'DISPUTE_MANAGER',
    avatar_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=250',
    last_login: '1 hour ago',
    is_active: true,
  },
  {
    id: 'adm_03',
    email: 'moderator.sarah@studynotehub.com',
    full_name: 'Sarah Adeleke (Content Moderator)',
    permission: 'CONTENT_MODERATOR',
    avatar_url: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&q=80&w=250',
    last_login: '25 mins ago',
    is_active: true,
  },
  {
    id: 'adm_04',
    email: 'finance.auditor@studynotehub.com',
    full_name: 'Ibrahim Danjuma (Financial Auditor)',
    permission: 'FINANCE_AUDITOR',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=250',
    last_login: '3 hours ago',
    is_active: true,
  },
];

export const MOCK_SUPER_ADMIN_PROFILE: Profile = {
  id: 'usr_super_admin_orukari',
  email: 'orukari878@gmail.com',
  full_name: 'Super Admin',
  role: 'ADMIN',
  admin_permission: 'SUPER_ADMIN',
  avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=250',
  wallet_balance: 500000.00,
  is_verified_writer: true,
  created_at: new Date().toISOString(),
};

export const MOCK_CURRENT_USER: Profile = {
  id: 'usr_student_01',
  email: 'alex.adebayo@university.edu.ng',
  full_name: 'Alex Adebayo',
  role: 'STUDENT',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
  institution: 'University of Lagos (UNILAG)',
  department: 'Computer Science',
  wallet_balance: 18500.00,
  is_verified_writer: false,
  writer_skills: ['Python', 'Technical Writing', 'Data Structures'],
  writer_rating: 4.9,
  total_reviews: 14,
  total_completed_orders: 8,
  created_at: '2025-01-15T09:00:00Z',
};

export const MOCK_WRITERS: Profile[] = [
  {
    id: 'usr_writer_01',
    email: 'dr.emeka@writers.hub',
    full_name: 'Dr. Emeka Okafor',
    role: 'WRITER',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250',
    institution: 'University of Ibadan',
    department: 'Economics & Statistics',
    bio: 'PhD Holder with 7+ years of experience in Econometric Modeling, SPSS, STATA, and Thesis Writing.',
    wallet_balance: 145000.00,
    is_verified_writer: true,
    writer_skills: ['Data Analysis', 'SPSS/STATA', 'Econometrics', 'Thesis / Dissertation', 'APA 7th'],
    writer_rating: 4.98,
    total_reviews: 128,
    total_completed_orders: 142,
    created_at: '2024-02-10T12:00:00Z',
  },
  {
    id: 'usr_writer_02',
    email: 'fatima.lawal@writers.hub',
    full_name: 'Barr. Fatima Lawal',
    role: 'WRITER',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
    institution: 'Ahmadu Bello University (ABU)',
    department: 'Faculty of Law',
    bio: 'Commercial Law researcher, specialized in Constitutional Law essays, Legal Briefs, and Case Law analysis.',
    wallet_balance: 92000.00,
    is_verified_writer: true,
    writer_skills: ['Legal Research', 'OSCOLA / Harvard', 'Case Briefs', 'Essays', 'Jurisprudence'],
    writer_rating: 4.95,
    total_reviews: 84,
    total_completed_orders: 97,
    created_at: '2024-05-18T10:00:00Z',
  },
  {
    id: 'usr_writer_03',
    email: 'engr.tunde@writers.hub',
    full_name: 'Engr. Tunde Bakare',
    role: 'WRITER',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=250',
    institution: 'Federal University of Technology Akure (FUTA)',
    department: 'Electrical & Software Engineering',
    bio: 'Senior Software Engineer & Academic Tutor. MATLAB, Python, Arduino, Circuit Design, and Final Year Projects.',
    wallet_balance: 110500.00,
    is_verified_writer: true,
    writer_skills: ['MATLAB', 'Python / ML', 'Software Architecture', 'Hardware Design', 'IEEE Format'],
    writer_rating: 4.92,
    total_reviews: 115,
    total_completed_orders: 120,
    created_at: '2024-01-20T14:30:00Z',
  },
];

export const MOCK_DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc_01',
    uploader_id: 'usr_writer_01',
    uploader: MOCK_WRITERS[0],
    title: 'Complete Macroeconomics (ECO 201) Lecture Notes & Past Questions Solutions',
    description: 'Comprehensive 65-page semester master note covering IS-LM Curves, Fiscal/Monetary Policy, Inflation-Unemployment Phillips Curves with 5 years solved past exams.',
    course_code: 'ECO 201',
    course_title: 'Principles of Macroeconomics',
    institution: 'University of Lagos (UNILAG)',
    faculty: 'Social Sciences',
    department: 'Economics',
    level: '200L',
    file_path: 'documents/eco201-complete-master-notes.pdf',
    preview_file_path: 'previews/eco201-preview.pdf',
    file_type: 'pdf',
    file_size_bytes: 4820000,
    page_count: 65,
    price: 1500.00,
    downloads_count: 342,
    status: 'APPROVED',
    rating: 4.9,
    created_at: '2025-02-01T10:00:00Z',
  },
  {
    id: 'doc_02',
    uploader_id: 'usr_writer_03',
    uploader: MOCK_WRITERS[2],
    title: 'Data Structures & Algorithms in C++ & Python (CSC 301) Handbook',
    description: 'Concise, illustrated lecture summaries with Big-O Cheat Sheets, Binary Search Trees, Graph Traversals, and Dynamic Programming templates.',
    course_code: 'CSC 301',
    course_title: 'Data Structures and Algorithms',
    institution: 'Covenant University',
    faculty: 'Science & Technology',
    department: 'Computer Science',
    level: '300L',
    file_path: 'documents/csc301-dsa-handbook.pdf',
    file_type: 'pdf',
    file_size_bytes: 6140000,
    page_count: 82,
    price: 2000.00,
    downloads_count: 512,
    status: 'APPROVED',
    rating: 4.96,
    created_at: '2025-01-20T15:30:00Z',
  },
  {
    id: 'doc_03',
    uploader_id: 'usr_student_01',
    uploader: MOCK_CURRENT_USER,
    title: 'GST 101: Use of English & Communication Skills - Quick Revision Flashcards',
    description: 'High-yield summary of Sentence Structures, Concord Rules, Idiomatic Expressions, and common CBT exam traps.',
    course_code: 'GST 101',
    course_title: 'Use of English',
    institution: 'University of Ibadan',
    faculty: 'General Studies',
    department: 'Arts',
    level: '100L',
    file_path: 'documents/gst101-revision.pdf',
    file_type: 'pdf',
    file_size_bytes: 1850000,
    page_count: 24,
    price: 0.00, // FREE
    downloads_count: 1240,
    status: 'APPROVED',
    rating: 4.85,
    created_at: '2025-02-10T08:15:00Z',
  },
  {
    id: 'doc_04',
    uploader_id: 'usr_writer_02',
    uploader: MOCK_WRITERS[1],
    title: 'Law of Contract (LAW 203) Case Summaries & Exam Frameworks',
    description: 'Key landmark cases in Offer & Acceptance, Consideration, Intention to create legal relations, with template problem-question answering structures (IRAC).',
    course_code: 'LAW 203',
    course_title: 'Nigerian Law of Contract',
    institution: 'Obafemi Awolowo University (OAU)',
    faculty: 'Faculty of Law',
    department: 'Commercial Law',
    level: '200L',
    file_path: 'documents/law203-contracts-irac.pdf',
    file_type: 'pdf',
    file_size_bytes: 3200000,
    page_count: 48,
    price: 1200.00,
    downloads_count: 280,
    status: 'APPROVED',
    rating: 4.91,
    created_at: '2025-02-05T12:00:00Z',
  },
  {
    id: 'doc_pending_01',
    uploader_id: 'usr_student_01',
    uploader: MOCK_CURRENT_USER,
    title: 'Biochemistry (BCH 301) Enzymology & Metabolic Pathways Handwritten Charts',
    description: 'Full glycolysis, TCA cycle, and electron transport chain breakdown with enzyme cofactor tables.',
    course_code: 'BCH 301',
    course_title: 'Metabolism of Carbohydrates',
    institution: 'University of Lagos (UNILAG)',
    faculty: 'Basic Medical Sciences',
    department: 'Biochemistry',
    level: '300L',
    file_path: 'documents/bch301-enzymes.pdf',
    file_type: 'pdf',
    file_size_bytes: 5200000,
    page_count: 32,
    price: 1000.00,
    downloads_count: 0,
    status: 'PENDING',
    rating: 5.0,
    created_at: '2025-02-18T11:00:00Z',
  },
];

export const MOCK_ORDERS: OrderItem[] = [
  {
    id: 'ord_101',
    student_id: 'usr_student_01',
    student: MOCK_CURRENT_USER,
    writer_id: 'usr_writer_01',
    writer: MOCK_WRITERS[0],
    title: 'Chapter 4 & 5 Data Analysis on Fintech Adoption in Emerging Markets',
    service_type: 'Data Analysis & Project Chapter',
    subject_area: 'Economics & Banking',
    academic_level: 'Undergraduate (Final Year)',
    pages_count: 18,
    word_count: 4500,
    citation_style: 'APA 7th',
    deadline: '2025-03-05T18:00:00Z',
    instructions: 'Perform Multiple Linear Regression in SPSS for 250 survey respondents. Provide Descriptive Statistics, Correlation Matrix, ANOVA table, hypothesis testing, and recommendations.',
    budget: 35000.00,
    platform_fee: 5250.00,
    status: 'IN_PROGRESS',
    escrow_status: 'HELD_IN_ESCROW',
    created_at: '2025-02-14T10:00:00Z',
  },
  {
    id: 'ord_102',
    student_id: 'usr_student_01',
    student: MOCK_CURRENT_USER,
    writer_id: 'usr_writer_02',
    writer: MOCK_WRITERS[1],
    title: 'Comparative Analysis of Data Privacy Regulations: GDPR vs. NDPR',
    service_type: 'Term Paper / Essay',
    subject_area: 'Cyber Law & Governance',
    academic_level: 'Post-Graduate (Masters)',
    pages_count: 12,
    word_count: 3000,
    citation_style: 'Harvard',
    deadline: '2025-02-28T23:59:00Z',
    instructions: 'Critically analyze enforcement mechanisms, compliance penalties, and cross-border data transfer limitations under both frameworks. 100% plagiarism-free required.',
    budget: 25000.00,
    platform_fee: 3750.00,
    status: 'IN_REVIEW',
    escrow_status: 'HELD_IN_ESCROW',
    created_at: '2025-02-12T14:30:00Z',
  },
  {
    id: 'ord_dispute_01',
    student_id: 'usr_student_01',
    student: MOCK_CURRENT_USER,
    writer_id: 'usr_writer_03',
    writer: MOCK_WRITERS[2],
    title: 'Design and Simulation of an IoT Smart Agriculture Irrigation System',
    service_type: 'Final Year Capstone Project',
    subject_area: 'Electrical & Electronics Engineering',
    academic_level: 'Undergraduate',
    pages_count: 35,
    word_count: 9000,
    citation_style: 'IEEE',
    deadline: '2025-02-20T12:00:00Z',
    instructions: 'Includes Chapter 1-5 writeup, Proteus simulation circuit, ESP32 Arduino code, and Blynk mobile dashboard configuration.',
    budget: 65000.00,
    platform_fee: 9750.00,
    status: 'DISPUTED',
    escrow_status: 'DISPUTE_HOLD',
    dispute_reason: 'Student claims Arduino code simulation crashes with Blynk library version 2. Writer insists code is tested and submitted before deadline.',
    created_at: '2025-02-15T16:00:00Z',
  },
];

export const MOCK_PAYOUT_REQUESTS: PayoutRequest[] = [
  {
    id: 'pay_01',
    writer_id: 'usr_writer_01',
    writer: MOCK_WRITERS[0],
    amount: 55000.00,
    bank_name: 'GTBank (Guaranty Trust)',
    account_number: '0129482910',
    account_name: 'Dr. Emeka Okafor',
    status: 'PENDING',
    created_at: '2025-02-18T10:15:00Z',
  },
  {
    id: 'pay_02',
    writer_id: 'usr_writer_02',
    writer: MOCK_WRITERS[1],
    amount: 40000.00,
    bank_name: 'Access Bank',
    account_number: '0719284918',
    account_name: 'Fatima Lawal',
    status: 'PENDING',
    created_at: '2025-02-18T12:30:00Z',
  },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'txn_01',
    user_id: 'usr_student_01',
    amount: 50000.00,
    fee: 0.00,
    type: 'WALLET_DEPOSIT',
    gateway: 'PAYSTACK',
    reference: 'SNH_PSTK_DEP_8832',
    description: 'Wallet funding via Paystack Debit Card',
    created_at: '2025-02-10T14:20:00Z',
  },
  {
    id: 'txn_02',
    user_id: 'usr_student_01',
    amount: 1500.00,
    fee: 0.00,
    type: 'NOTE_PURCHASE',
    gateway: 'WALLET',
    reference: 'SNH_PUR_ECO201_491',
    description: 'Purchased ECO 201 Macroeconomics Master Notes',
    created_at: '2025-02-11T09:12:00Z',
  },
  {
    id: 'txn_03',
    user_id: 'usr_student_01',
    amount: 35000.00,
    fee: 0.00,
    type: 'ESCROW_LOCK',
    gateway: 'WALLET',
    reference: 'SNH_ESC_ORD101_332',
    description: 'Escrow lock for Order #ord_101 (Data Analysis)',
    created_at: '2025-02-14T10:05:00Z',
  },
  {
    id: 'txn_04',
    user_id: 'adm_super_01',
    amount: 5250.00,
    fee: 0.00,
    type: 'PLATFORM_FEE',
    reference: 'SNH_FEE_ORD101',
    description: '15% Platform Commission collected for Order #ord_101',
    created_at: '2025-02-14T10:05:00Z',
  },
];

export const CATEGORIES = [
  'All Materials',
  'Computer Science & IT',
  'Economics & Finance',
  'Engineering',
  'Law & Jurisprudence',
  'Medical & Health Sciences',
  'Business Administration',
  'Arts & Humanities',
  'Natural Sciences',
];

export const INSTITUTIONS = [
  'All Universities',
  'University of Lagos (UNILAG)',
  'University of Ibadan (UI)',
  'Covenant University',
  'Obafemi Awolowo University (OAU)',
  'Ahmadu Bello University (ABU)',
  'Federal University of Technology Akure (FUTA)',
  'University of Nigeria, Nsukka (UNN)',
  'University of Benin (UNIBEN)',
  'Babcock University',
];

export const LEVELS = ['All Levels', '100L', '200L', '300L', '400L', '500L', 'Post-Graduate / Masters', 'PhD'];
